# Exclude glob
# The paths are relative to obsidian_folder_path_str
# - Start with slash to target specific folder: /subfolder
# - Target any folder with name "subfolder": subfolder
# Glob patterns supported for copy_vault_to_tempdir_method: shutil, shutil_walk, and for rsync for as far as rsync supports it natively
#   When turning off copy_vault_to_tempdir, glob patterns are fully supported.
# Rules are case sensitive if your filesystem is.
exclude_glob:
  - "/.obsidian"
  - "/.trash"
  - "/.DS_Store"
  - "/.git"
  - "/excalidraw"
  - "/books"
  - "/datasets"
  - "prv_*"

html_template_path_str: 'templates/obsidianhtml.html'

obsidian_entrypoint_path_str: 'my activities.md'

# Input and output path of markdown files
# This can be an absolute or a relative path (relative to the working directory when calling obsidianhtml)
# Use full path or relative path, but don't use ~/
md_folder_path_str:  '/home/inom/Projects/main/wiki_html/output/md'

# Markdown entrypoint path
# This has to be md_folder_path_str + '/index.md' when toggles/compile_md == True
# This can be an absolute or a relative path (relative to the working directory when calling obsidianhtml)
# Use full path or relative path, but don't use ~/
md_entrypoint_path_str: '/home/inom/Projects/main/wiki_html/output/md/index.md'

# Output path of HTML files
# This can be an absolute or a relative path (relative to the working directory when calling obsidianhtml)
# Use full path or relative path, but don't use ~/
html_output_folder_path_str: '/home/inom/Projects/main/wiki_html/docs'

# If extended logging is enabled under toggles/extended_logging
# Extra information is written to this folder
log_output_folder_path_str: '/home/inom/Projects/main/wiki_html/output/log'

toggles:
  strict_line_breaks: true

  features:
    styling:
      layout: documentation               # documentation, tabs, minimal
      max_note_width: 80rem              # not supported for layout: tabs
      add_dir_list: True                  # show directory contents in one of the panes (only documentation layout)

    side_pane:              # only valid for documentation layout
      left_pane:
        enabled: True

      right_pane:
        enabled: False

# Will be inputted into the Html template as page title
# Not used anywhere else atm.
site_name: "Inom's working notes"

